#!/bin/bash
# Theme manager for plank!
cwd=$(pwd)

# List
if [ "$1" == "-l" ];then
    cd ~ && cd ".local/share/plank/themes" 
    echo "------------------"
    echo "Themes installed"
    echo "------------------"
    [ "$(ls -A)" ] && echo "" || echo "👉️ Go ahead and install some themes first! https://www.gnome-look.org/browse?cat=273&ord=latest"
    ls
    cd ~ && cd $cwd
    fi

# Theme uninstaller
if [ "$1" == "-r" ];then
    if [ -z "$2" ];then
        echo "🤒️ Name cannot be empty! Dude!"   
        else
            cd ~ && cd ".local/share/plank/themes" 
            if [ -d "$2" ];then
                rm -rf "$2" && cd ~ && cd $cwd
                echo "🗑️ $2 theme has been uninstalled!"
            else
                cd ~ && cd $cwd
                echo "🧐️ $2 theme it is not installed!"
            fi
        fi
    fi

# Theme installer
if [ -z "$1" ];then
    echo "👉️ Type the filename of your theme!"
    else
        if [ $1 != "-r" ] && [ $1 != "-h" ] && [ $1 != "-l" ] && [ $1 != "--install" ];then
            if [ -f $1 ];then
                echo "👊️😎️ $1 theme has been installed!"
                tar -xf $1 -C ~/.local/share/plank/themes
            else
                echo "😕️ $1 theme doesn't exist in planker directory!"
            fi
        fi
    fi

# Plank installer
if [ "$1" == "--install" ];then
    if [ ! -d "planker" ];then
        mkdir planker
    fi
    chmod a+x plankerapp
    cp plankerapp planker
    mv planker ~/
    sudo echo "alias planker=\"cd \$HOME\/planker/ && ./plankerapp\"" >> ~/.bash_aliases
    echo "👊️😎️ planker in now installed system-wide!"
    echo "- Reopen this terminal to make 'planker' command available"
    fi

# Help
if [ "$1" == "-h" ];then
    echo "-----------"
    echo "Help guide"
    echo "-----------"
    echo "[no arguments] (installs a theme)"
    echo "[-r] (uninstalls a theme)"
    echo "[-l] (list all themes installed)"
    echo "[-h] (shows this help)"
    echo "[--install] (installs app system-wide)"
    fi
